### ISSUE TITLE
Automated Deployment

### ISSUE THREAD

**Issue by ThomasThelen** [OHI-Science/OHI-website#128]
Now that we have a dedicated server, we should hook up an automated deployment system. The DataONE website uses Travis CI for this and we'll do the same.

There will be a bash script that handles sending the build website code over to our server. To do this, we'll first need to set up the build on Travis, and then store our Travis secrets in an encrypted file.

**Comment by robyngit** [comment]
Note that we should use a specific version of Hugo, like [we do for the DataONE site](https://github.com/DataONEorg/dataone-web/blob/bbdcaf625daa89043a9064aca258c1957ccd10d1/.travis.yml#L15), and not just the latest version, like we currently have in the demo GH action.

**Comment by mbjones** [comment]
@ThomasThelen The entrypoint should be one of our production servers, so that it will be available when needed. Another option than using a separate entrypoint would be for us to open the firewall on juno to the github servers, if we can identify what those are, and assuming they don't change frequently. Then, the web build via GHA could copy the files directly. The advantage of this is that our same CI process that we use for testing can be used for deployment. Let's talk to @nickatnceas about the firewall configuration.
